### ISSUE TITLE
Restart IPS simulation from LATEST

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#23]
@elwasif @diemsj @bernhold @batchelordb 

I'd like to be able to restart an IPS simulation from the latest entry in the $RESTART_ROOT, i.e., something like ...

```
SIMULATION_MODE = RESTART
RESTART_TIME = LATEST
RESTART_ROOT = ${SIM_ROOT}

[TIME_LOOP]
MODE = REGULAR
START = ${RESTART_TIME}
FINISH = ${RESTART_TIME} + 1
NSTEP = 1
```

This can be done with shell scripts already, but is rather messy. I'd rather it be a feature of the IPS. This is likely to require basic arithmetic parsing in the config file, or the possibility of backtick-enclosed type execution to return variables. 

Is this something plausible to do?

**Comment by elwasif** [comment]
SVN r186 (just committed) should have these features. More testing (always) welcome.

**Comment by dlg0** [comment]
Oh yeah! I'll test and get back to you. Thanks!

**Comment by dlg0** [comment]
So this is the syntax I tried ...

```
 43 SIMULATION_MODE = RESTART # NORMAL or RESTART
 44 RESTART_TIME = LATEST # LATEST or float (e.g., 2.5)
 45 RESTART_ROOT = $SIM_ROOT
```

```
467 [TIME_LOOP]
468     MODE = REGULAR # REGULAR or EXPLICIT
469     START = $RESTART_TIME
470     FINISH = $RESTART_TIME + 1
471     NSTEP = 1
```
but it failed with ...

```
2015-06-25 10:17:06,418 FRAMEWORK       ERROR    received a failure message from component thisSim@minimal_state_init@1 : (Exception('Invalid TIME_LOOP value of FINISH = LATEST + 1',),)
```

Thoughts?

**Comment by elwasif** [comment]
Should be fixed now

**Comment by dlg0** [comment]
```
2015-06-25 10:49:17,058 FRAMEWORK       ERROR    Problem initializing managers
Traceback (most recent call last):
  File "/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/ips.py", line 272, in __init__
    self.ftb)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 430, in initialize
    self._initialize_sim(sim_data)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 626, in _initialize_sim
    component_id = self._create_component(comp_conf, sim_data)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 717, in _create_component
    services_proxy.__initialize__(new_component)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/services.py", line 208, in __initialize__
    if conf['SIMULATION_MODE'] == 'RESTART':
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 567, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'SIMULATION_MODE'
```

**Comment by elwasif** [comment]
One more time (Damn copy paste)

**Comment by dlg0** [comment]
```
2015-06-25 11:02:39,241 FRAMEWORK       ERROR    Problem initializing managers
Traceback (most recent call last):
  File "/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/ips.py", line 272, in __init__
    self.ftb)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 430, in initialize
    self._initialize_sim(sim_data)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 626, in _initialize_sim
    component_id = self._create_component(comp_conf, sim_data)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 717, in _create_component
    services_proxy.__initialize__(new_component)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/services.py", line 209, in __initialize__
    if conf['TIME_LOOP']['RESTART_TIME'] == 'LATEST':
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 567, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'TIME_LOOP'
```

**Comment by elwasif** [comment]
On 06/25/2015 02:16 PM, David L Green wrote:
> |2015-06-25 11:02:39,241 FRAMEWORK ERROR Problem initializing managers
> Traceback (most recent call last): File
> "/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/ips.py",
> line 272, in __init__ self.ftb) File
> "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py",
> line 430, in initialize self._initialize_sim(sim_data) File
> "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py",
> line 626, in _initialize_sim component_id =
> self._create_component(comp_conf, sim_data) File
> "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py",
> line 717, in _create_component
> services_proxy.__initialize__(new_component) File
> "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/services.py",
> line 209, in __initialize__ if conf['TIME_LOOP']['RESTART_TIME'] ==
> 'LATEST': File
> "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py",
> line 567, in __getitem__ val = dict.__getitem__(self, key) KeyError:
> 'TIME_LOOP' |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ORNL-Fusion/ips-atom/issues/23#issuecomment-115352064>.
>
Try now - again

-- 
Wael R. Elwasif, PhD.
Research Staff Member
Computer Science Research Group
Oak Ridge National Laboratory
P.O. Box 2008, Bldg. 5600, MS 6016
Oak Ridge, TN 37831-6016

Office : (865)241-0002
Fax:     (865)576-5491

**Comment by dlg0** [comment]
One more time ;)

```
2015-06-26 11:10:58,341 FRAMEWORK       ERROR    Problem initializing managers
Traceback (most recent call last):
  File "/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/ips.py", line 272, in __init__
    self.ftb)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 430, in initialize
    self._initialize_sim(sim_data)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 626, in _initialize_sim
    component_id = self._create_component(comp_conf, sim_data)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 717, in _create_component
    services_proxy.__initialize__(new_component)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/services.py", line 209, in __initialize__
    if self.sim_conf['TIME_LOOP']['RESTART_TIME'] == 'LATEST':
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 567, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'RESTART_TIME
```

**Comment by elwasif** [comment]
Next time, try now.

**Comment by dlg0** [comment]
Did you push something to SourceForge? I don't see any updates.

**Comment by elwasif** [comment]
It was stuck in background, it's in now.

**Comment by dlg0** [comment]
After getting rid of some other issues, I think I have my first successful test of this feature. 

Thanks Wael!
