### ISSUE TITLE
Toric wrapper error when INPUT_SUFFIX not present in config file

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#31]
@elwasif 
@batchelordb 
@diemsj 

`/project/projectdirs/atom/users/greendl1/runs/diem_tsc_toric_err1`

The toric wrapper has logic in it to account for when there is no `INPUT_SUFFIX` specified in the config file ...

```
106         try:
107             suffix = self.INPUT_SUFFIX
108             have_suffix = True
109         # If suffix is not empty put an underscore in front of it.
110             if len(suffix) > 0:
111                 print 'INPUT_SUFFIX = ', suffix
112                 suffix = '_' + suffix
113         # If suffix is empty you don't really have one
114             else:
115                 have_suffix = False
116         except:
117             have_suffix = False
118             pass
```

However, when I actually run without that config parameter I get the following error ...

log.warning
```
 67 2015-09-10 12:21:47,341 rf_ic_toric_4   ERROR    Error in call to toric_init
 68 Traceback (most recent call last):
 69   File "/project/projectdirs/atom/users/greendl1/code/ips-wrappers/ips-toric/rf_ic_toric_abr_mcmd.py", line 107, in init
 70     suffix = self.INPUT_SUFFIX
 71 AttributeError: 'toric' object has no attribute 'INPUT_SUFFIX'
 72 2015-09-10 12:21:47,366 driver__basic_time_step_driver_2 DEBUG    ###### Raising Error in call to toric_init
 73 2015-09-10 12:21:47,381 driver__basic_time_step_driver_2 ERROR    Uncaught Exception in component method.
 74 Traceback (most recent call last):
 75   File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/component.py", line 121, in __run__
 76     retval = method(*args)
 77   File "/project/projectdirs/atom/users/greendl1/code/ips-wrappers/generic-drivers/basic_time_step_driver.py", line 72, in ste
 78     self.component_call(services,port_name,port_dict[port_name],init_mode,t)
 79   File "/project/projectdirs/atom/users/greendl1/code/ips-wrappers/generic-drivers/basic_time_step_driver.py", line 174, in co
 80     services.call(comp, mode, time)
 81   File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/services.py", line 444, in call
 82     retval = self.wait_call(call_id, block=True)
 83   File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/services.py", line 462, in wait_call
 84     response = self._get_service_response(msg_id, block=True)
 85   File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/services.py", line 359, in _get_service_response
 86     raise response.args[0]
 87 Exception: Error in call to toric_init
```

log.framework
```
2015-09-10 12:21:43,600 FRAMEWORK       WARNING  RM: listOfNodes = [('1378', '24'), ('3088', '24'), ('3089', '24'), ('3090', '24'), ('3218', '24'), ('3219', '24'), ('3222', '24'), ('3223', '24'), ('3224', '24'), ('3225', '24'), ('3226', '24'), ('3227', '24'), ('3228', '24'), ('3229', '24'), ('3230', '24')]
2015-09-10 12:21:43,600 FRAMEWORK       WARNING  RM: max_ppn = 24
2015-09-10 12:21:43,601 FRAMEWORK       WARNING  Using user set procs per node: 24
2015-09-10 12:21:43,601 FRAMEWORK       WARNING  RM: 15 nodes and 24 processors per node
2015-09-10 12:21:47,396 FRAMEWORK       ERROR    received a failure message from component thisSim@basic_time_step_driver@2 : (Exception('Error in call to toric_init',),)
```

I added the `pass` statement thinking it was just that the exception was not being let go after being dealt with by setting the `have_suffix = False`, but the error persists. Obviously my understanding is flawed. Help appreciated :)

**Comment by elwasif** [comment]
Arggggggggg.
Same bad exception handling problem. The error message in log.warning  `Error in call to toric_init` appears when the subprocess call to `do_toric_init_abr` returns non-zero - no exception is caught. Yet, the if block calls `self.services.exception(logMsg)` which prints the stack trace from the most recent exception caught, which happens to be the one associated with the INPUT_SUFFIX processing

**Comment by dlg0** [comment]
Ah. Excellent. Thanks.


________________________________
