### ISSUE TITLE
  raise Exception('No such file : %s in directory %s', file, src_dir)

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#34]
@elwasif 

Can we adjust the IPS such that this error message prints the file and directory to the log? At present it doesn't actually print the file and dir, only the below msg.

At least I think this is within the IPS itself (at line 126 as indicated), although it could be some artifact of poor component wrapper exception handling.

```
2015-09-29 10:53:41,654 FRAMEWORK       WARNING  Using user set procs per node: 24
2015-09-29 10:53:41,655 FRAMEWORK       WARNING  RM: 15 nodes and 24 processors per node
2015-09-29 10:53:41,974 FWK_COMP_runspaceInitComponent_8 ERROR    Uncaught Exception in component method.
Traceback (most recent call last):
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/component.py", line 121, in __run__
    retval = method(*args)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/runspaceInitComponent.py", line 116, in init
    os.path.basename(file))
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/ipsutil.py", line 126, in writeToContainer
    raise Exception('No such file : %s in directory %s', file, src_dir)
```

**Comment by elwasif** [comment]
Done, it was a bug in the way the exeception was formatted

**Comment by dlg0** [comment]
Thanks!
