### ISSUE TITLE
FRAMEWORK ERROR Problem initializing managers

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#5]
@ORNL-Fusion/ips-support-team 
So I've aggravated my config file, and the IPS is trying to tell me that. Is there some info in the below log file that tells me where the error is in my config file?

Thanks, 
David.

```
greendl1@edison01:/project/projectdirs/atom/users/greendl1/diem_tsc> cat this.log
2015-05-06 10:15:21,463 FRAMEWORK       ERROR    Problem initializing managers
Traceback (most recent call last):
  File "/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/ips.py", line 272, in __init__
    self.ftb)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 410, in initialize
    fwk_sim_conf = conf.dict()
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 787, in dict
    this_entry = this_entry.dict()
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 785, in dict
    this_entry = self[entry]
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 570, in __getitem__
    return self._interpolate(key, val)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 562, in _interpolate
    return engine.interpolate(key, value)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 365, in interpolate
    value = recursive_interpolate(key, value, self.section, {})
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 343, in recursive_interpolate
    k, v, s = self._parse_match(match)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 451, in _parse_match
    value, section = self._fetch(key)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configobj.py", line 399, in _fetch
    raise MissingInterpolationOption(key)
MissingInterpolationOption: missing option "INPUT_DIR_SIM" in interpolation.
2015-05-06 10:15:22,552 FRAMEWORK       ERROR    exception encountered while cleaning up config_manager
Traceback (most recent call last):
  File "/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/ips.py", line 915, in terminate_all_sims
    self.config_manager.terminate(status)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 993, in terminate
    self.log_process.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```

**Comment by dlg0** [comment]
The error 

```
MissingInterpolationOption: missing option "INPUT_DIR_SIM" in interpolation.
```

was due to an undefined variable $INPUT_DIR_SIM in the config file.
