### ISSUE TITLE
ERROR    Error in configuration file : NAME = nubeam_jm

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#6]
@ORNL-Fusion/ips-support-team 

I'm trying to replace one NUBEAM component with the one that JM created. However, my run in 

`/project/projectdirs/atom/users/greendl1/diem_tsc_error2`

is failing with the following ...

```
greendl1@edison01:/project/projectdirs/atom/users/greendl1/diem_tsc_error2> cat this.log
2015-05-06 11:03:48,482 FRAMEWORK       ERROR    Error in configuration file : NAME = nubeam_jm   SCRIPT = /project/projectdirs/atom/atom-install-edison/ips-wrappers/ips-fastran/src/nubeam.py
2015-05-06 11:03:48,489 FRAMEWORK       ERROR    Error instantiating IPS component nubeam_jm From nubeam
Traceback (most recent call last):
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 693, in _create_component
    component_class = getattr(module, class_name)
AttributeError: 'module' object has no attribute 'nubeam_jm'
2015-05-06 11:03:48,496 FRAMEWORK       ERROR    Problem initializing managers
Traceback (most recent call last):
  File "/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/ips.py", line 272, in __init__
    self.ftb)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 427, in initialize
    self._initialize_sim(sim_data)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 623, in _initialize_sim
    component_id = self._create_component(comp_conf, sim_data)
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 693, in _create_component
    component_class = getattr(module, class_name)
AttributeError: 'module' object has no attribute 'nubeam_jm'
```

I was confused by the line 

`2015-05-06 11:03:48,489 FRAMEWORK       ERROR    Error instantiating IPS component nubeam_jm From nubeam`

but it turns out that there is simply a line break missing there, and that the 'nubeam' it is referring to is the 'nubeam.py' of the wrapper script. @elwasif Perhaps a line break after the framework errors would be helpful?

Otherwise I don't know where to go from here.

Any ideas?

**Comment by elwasif** [comment]
@dlg0  so I am confused, it still doesn't work after you added the line break?

**Comment by elwasif** [comment]
I think I see the problem, the NAME field is the name of the Python class in the .py file, so there's no nubeam_jm class in $FASTRAN_ROOT/src/nubeam.py. The python class name is nubeam

**Comment by dlg0** [comment]
@elwasif The line break stuff is only referring to the log file. i.e., when read verbatim the log file reads 

`2015-05-06 11:03:48,489 FRAMEWORK ERROR Error instantiating IPS component nubeam_jm From nubeam`

which confused me. It would be clearer if it read ...

```
2015-05-06 11:03:48,489 FRAMEWORK ERROR Error instantiating IPS component nubeam_jm 

From /project/projectdirs/atom/atom-install-edison/ips-wrappers/ips-fastran/src/nubeam.py
Traceback (most recent call last):
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/configurationManager.py", line 693, in _create_component
    component_class = getattr(module, class_name)
```

So I didn't actually add any line breaks, just had some trouble interpreting the error due to the positioning of them.

**Comment by dlg0** [comment]
Ah, OK. I didn't pay enough attention to the IPS documentation where it does say that. Since CLASS and SUB_CLASS refer to arbitrary names, I had assumed that NAME did the same. I originally changed it because I feared it would conflict with the NAME value of my alternate NUBEAM port.

Thanks.
