### ISSUE TITLE
pstool error

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/ips-atom#9]
@parkjm 

In the following run ...

```
/global/project/projectdirs/atom/users/greendl1/diem_tsc_error7
```

I am getting a `pstool` related error. No doubt I'm aggravating it somehow ...

```
greendl1@nid02432:/global/project/projectdirs/atom/users/greendl1/diem_tsc> cat ss31615.log
2015-05-08 11:49:33,054 fastran_init_fastran_init_1 ERROR    Uncaught Exception in component method.
Traceback (most recent call last):
  File "/global/project/projectdirs/atom/atom-install-edison/ips-gnu-sf/bin/component.py", line 121, in __run__
    retval = method(*args)
  File "/project/projectdirs/atom/atom-install-edison/ips-wrappers/ips-fastran/src/fastran_init.py", line 163, in step
    raise Exception('Error executing ', pstool_bin)
Exception: ('Error executing ', '/project/projectdirs/atom/atom-install-edison/binaries/pstool/default/pstool')
```

and

```
greendl1@nid02432:/global/project/projectdirs/atom/users/greendl1/diem_tsc> cat work/fastran_init_fastran_init_1/pstool_init.log
PGFIO-F-239/namelist read/unit=99/entity name is not member of group.
 File name = inps    formatted, sequential access   record = 21
 In source file pstool.f90, at line number 318
```

**Comment by dlg0** [comment]
@parkjm 
If you could point me in the direction of the pstool source I can have a go a tracking this down myself.

**Comment by dlg0** [comment]
This may have been a problem with using an old version of `pstool`. The one I copied from @parkjm home area on Edison to `$ATOM/atom-install-edision/binaries/pstool/default` appears different to the restored version in `ips-wrappers/ips-fastran/bin` ?
